### ISSUE TITLE
Mise en place de l'authentification

### ISSUE THREAD

**Issue by alkomaJunior** [alkomaJunior/alkoma_jr_blog#5]
Au cours de cette cinquième étape nous aurons à développer les pages d'authentification et les différents espaces de travail de chaque utilisateurs.

**Comment by fatima-elboubakri** [comment]
sur **UsersController** 

- il faut enlever le code dev dans la ligne 64 et 55 (var_dump)
- il faut pensé a envoyer une liste comme paramètre de la fonction "render" dans la ligne  68

**Comment by fatima-elboubakri** [comment]
il faut ajouter une petite description pour la fonction _rules()_ dans _Users.php_

**Comment by alkomaJunior** [comment]
Tâche terminée avec succès
